export const SHEETS_CONFIG = {
  CODE_COLUMN: process.env.CODE_COLUMN || 'E',
  SHEET_NAME: process.env.SHEET_NAME || 'Sheet1',
  COLUMN_MAPPINGS: {
    startingKm: 'O',
    endingKm: 'P',
    shiftStart: 'Q',
    loadOut: 'R',
    firstStop: 'S',
    lastStop: 'T',
    lastReattempt: 'U',
    stationReturn: 'V',
    clockOut: 'W',
    zone: 'X',
    uta: 'Y',
    utl: 'Z',
    nsl: 'AA',
    bc: 'AB',
    rejDmg: 'AC',
    oodt: 'AD',
    fdd: 'AE',
    extra: 'AG',
  },
  DATA_START_ROW: 2,
};
